# Generated by Django 5.0.1 on 2026-02-10 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_business_options_user_is_business_admin_and_more'),
        ('clients', '0002_add_title_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('note_type', models.CharField(choices=[('GENERAL', 'General Note'), ('MEETING', 'Meeting Notes'), ('PHONE_CALL', 'Phone Call'), ('EMAIL', 'Email'), ('DOCUMENT', 'Document'), ('COMPLIANCE', 'Compliance')], default='GENERAL', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='file_notes/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'File Note',
                'verbose_name_plural': 'File Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='Australia', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='postcode',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='quick_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Active Client'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='PROSPECT', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_file_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['business', 'status'], name='clients_cli_busines_1ceaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['primary_advisor'], name='clients_cli_primary_c42cab_idx'),
        ),
        migrations.AddField(
            model_name='filenote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_notes', to='clients.client'),
        ),
        migrations.AddField(
            model_name='filenote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filenote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_notes_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
