# Generated by Django 5.0.1 on 2026-02-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_filenote_file_remove_filenote_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileattachment',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fileattachment',
            old_name='file_size',
            new_name='size',
        ),
    ]
