# Generated by Django 5.0.1 on 2026-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_allow_null_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_business_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADVISOR', 'Financial Advisor'), ('PARA_PLANNER', 'Paraplanner'), ('ADMIN_STAFF', 'Administrative Staff'), ('COMPLIANCE', 'Compliance Officer')], default='ADVISOR', max_length=20),
        ),
    ]
